In [34]:
import torch
# import lietorch
import pypose as pp
import mrob
import numpy as np
# import lietorch
from grad_utils import mult, mult_mrob

In [35]:
a = pp.SE3(pp.se3(torch.randn(6)).Exp())

In [36]:
T = a

print(T)
T = pp.Parameter(T)

optimizer = torch.optim.SGD([T], lr=1)
optimizer.zero_grad()

p = torch.randn(4)
t = T.Act(p) 
loss = t @ t.T
loss.backward()

SE3Type LieTensor:
LieTensor([-0.0074,  0.6383, -1.8424,  0.2250, -0.0997,  0.6023,  0.7594])


In [38]:
gg = torch.tensor(pp.randn_se3().tolist() + [0])
T.grad = gg
print(gg)

tensor([-0.1623, -1.0172, -0.1072, -0.5390, -0.1815, -1.3594,  0.0000])


In [39]:
dxi = pp.SE3(pp.se3(-T.grad.squeeze()[:-1]*1).Exp())

print(T.grad)

dxi.mul(T.detach())

tensor([-0.1623, -1.0172, -0.1072, -0.5390, -0.1815, -1.3594,  0.0000])


SE3Type LieTensor:
LieTensor([-1.7725,  1.3114, -0.9250,  0.4649, -0.0196,  0.8737,  0.1420])

In [40]:
optimizer.step()

In [43]:
[1,2,3,4,5][3:]

[4, 5]

: 

In [41]:
T

SE3Type Parameter:
Parameter containing:
Parameter(Parameter([-1.7725,  1.3114, -0.9250,  0.4649, -0.0196,  0.8737,  0.1420],
          requires_grad=True))

tensor([[[ 1.0000,  0.0000,  0.0000,  0.6241],
         [ 0.0000,  1.0000,  0.0000, -0.5463],
         [ 0.0000,  0.0000,  1.0000, -0.5395],
         [ 0.0000,  0.0000,  0.0000,  1.0000]]])

In [264]:
dxi.matrix()

tensor([[[  1.0000,   0.0000,   0.0000,   5.7315],
         [  0.0000,   1.0000,   0.0000, -12.3233],
         [  0.0000,   0.0000,   1.0000,   3.7363],
         [  0.0000,   0.0000,   0.0000,   1.0000]]])

In [265]:
T.add(T.grad)

tensor([[  5.7315, -12.3233,   3.7363,   0.0000,   0.0000,   0.0000]],
       grad_fn=<AddBackward0>)

In [266]:
T[0].matrix()

tensor([[ 0.8362, -0.5112, -0.1986,  0.6006],
        [ 0.5431,  0.8221,  0.1708, -0.4864],
        [ 0.0760, -0.2507,  0.9651,  0.0598],
        [ 0.0000,  0.0000,  0.0000,  1.0000]], grad_fn=<TransposeBackward0>)

In [188]:
T_[0]

tensor([[ 0.5917,  0.4512,  0.6681,  0.0770],
        [ 0.7851, -0.1345, -0.6046, -0.5809],
        [-0.1830,  0.8822, -0.4338,  0.0234],
        [ 0.0000,  0.0000,  0.0000,  1.0000]], grad_fn=<TransposeBackward0>)

In [148]:
lietorch.SE3(T)

SE3: size=torch.Size([4]), device=cpu, dtype=torch.float32

In [134]:
T = lietorch.SE3(T)

In [105]:
lietorch.SE3(torch.f)

<module 'lietorch' from '/mnt/sdb1/home/kbotashev/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/lietorch/__init__.py'>

In [237]:
T.grad

tensor([[ 0.0155, -1.1198, -0.1750,  0.0000,  0.0000,  0.0000]])

In [91]:
xi = torch.rand((1,6), dtype = torch.float64, requires_grad = True)
x = torch.rand((1,3), requires_grad=True, dtype = torch.float64)

dxi = torch.rand(6, requires_grad=True, dtype = torch.float64)

In [101]:
xi_ = pp.se3(xi)
xi_.requires_grad_()
T = pp.Exp(xi_)
dT = pp.Exp(pp.se3(dxi))

p = (dT @ T).Act(x)
L = p @ p.T
L.backward()

In [102]:
xi.grad

tensor([[ 2.3111,  2.4240,  0.9720,  0.6763, -0.2955, -0.8712]],
       dtype=torch.float64)

In [103]:
xi_mrob = xi.tolist()[3:] + xi.tolist()[:3]
x_mrob = np.array(x.tolist())
torch.tensor(mult_mrob(xi_mrob, x_mrob).tolist()[3:] + mult_mrob(xi_mrob, x_mrob).tolist()[:3])

TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. mrob.pybind.geometry.SE3()
    2. mrob.pybind.geometry.SE3(arg0: numpy.ndarray[numpy.float64[4, 4]])
    3. mrob.pybind.geometry.SE3(arg0: numpy.ndarray[numpy.float64[6, 1]])
    4. mrob.pybind.geometry.SE3(arg0: mrob.pybind.geometry.SE3)
    5. mrob.pybind.geometry.SE3(arg0: mrob::SO3, arg1: numpy.ndarray[numpy.float64[3, 1]])

Invoked with: [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]

In [52]:
xi_mrob = xi.tolist()[3:] + xi.tolist()[:3]
x_mrob = np.array(x.tolist())
torch.tensor(mult_mrob(xi_mrob, x_mrob).tolist()[3:] + mult_mrob(xi_mrob, x_mrob).tolist()[:3])

TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. mrob.pybind.geometry.SE3()
    2. mrob.pybind.geometry.SE3(arg0: numpy.ndarray[numpy.float64[4, 4]])
    3. mrob.pybind.geometry.SE3(arg0: numpy.ndarray[numpy.float64[6, 1]])
    4. mrob.pybind.geometry.SE3(arg0: mrob.pybind.geometry.SE3)
    5. mrob.pybind.geometry.SE3(arg0: mrob::SO3, arg1: numpy.ndarray[numpy.float64[3, 1]])

Invoked with: [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]

In [54]:
xi_ = pp.se3(xi)
T = pp.Exp(xi_)
dT = pp.Exp(pp.se3(dxi))

p = (T).Act(x)
L = p @ p.T
L.backward()

In [55]:
p

tensor([[0.8351, 0.6601, 0.4654]], dtype=torch.float64,
       grad_fn=<ViewBackward0>)

In [60]:
2 * p.double() @ torch.cat((torch.eye(3).double(), -pp.vec2skew(p)), 1)

RuntimeError: Tensors must have same number of dimensions: got 2 and 3

In [61]:
2* p @ torch.cat((torch.eye(3).double(), -pp.vec2skew((dT @ T).Act(x))), 1)

RuntimeError: Tensors must have same number of dimensions: got 2 and 3

In [77]:
x_hom = torch.cat((x,torch.tensor([1])))
torch.kron(x_hom, torch.eye(3)) @ dExpxi_dxi(T.matrix()[:-1,0], T.matrix()[:-1,1], T.matrix()[:-1,2], T.matrix()[:-1,3])[:12]

tensor([[ 1.0000,  0.0000,  0.0000,  0.0000,  0.7084, -0.5504],
        [ 0.0000,  1.0000,  0.0000, -0.7084,  0.0000,  1.1357],
        [ 0.0000,  0.0000,  1.0000,  0.5504, -1.1357,  0.0000]],
       dtype=torch.float64, grad_fn=<MmBackward0>)

In [69]:
torch.kron(x_hom, torch.eye(4)) @ dExpxi_dxi(T.matrix()[:-1,0], T.matrix()[:-1,1], T.matrix()[:-1,2], T.matrix()[:-1,3])

tensor([[ 0.0000,  0.0000,  0.0000, -0.1868, -0.2461, -0.1534],
        [ 0.4277,  0.0000,  0.0000,  0.6848,  0.1937,  0.9067],
        [ 0.0000,  0.4277,  0.0000, -0.0403, -0.3899,  0.1797],
        [ 0.0000,  0.0000,  0.4277, -0.5168,  0.1061, -0.7997]],
       dtype=torch.float64, grad_fn=<MmBackward0>)

In [ ]:
torch.kron(x_hom, torch.eye(3)) @ dExpxi_dxi(T.matrix()[:-1,0], T.matrix()[:-1,1], T.matrix()[:-1,2], T.matrix()[:-1,3])[:12]

In [48]:
p_hom

tensor([1.1357, 0.5504, 0.7084, 1.0000], dtype=torch.float64,
       grad_fn=<CatBackward0>)

In [8]:
def dExpxi_dxi(a = torch.tensor([1,0,0]),
               b=torch.tensor([0,1,0]),
               c=torch.tensor([0,0,1]),
               d=torch.tensor([0,0,0])):
    result = torch.zeros((16,6))
    # result = np.random.rand(16,6)
    result[9:12, :3] = torch.eye(3)
    
    
    
    result[:3, 3:] = -pp.vec2skew(a)
    result[3:6, 3:] = -pp.vec2skew(b)
    result[6:9, 3:] = -pp.vec2skew(c)
    result[9:12, 3:] = -pp.vec2skew(d)

    return result.double()

In [60]:
dExpxi_dxi(T.matrix()[:-1,0], T.matrix()[:-1,1], T.matrix()[:-1,2], T.matrix()[:-1,3])[:12]

tensor([[ 0.0000,  0.0000,  0.0000, -0.0000, -0.1755, -0.1183],
        [ 0.0000,  0.0000,  0.0000,  0.1755, -0.0000,  0.9773],
        [ 0.0000,  0.0000,  0.0000,  0.1183, -0.9773, -0.0000],
        [ 0.0000,  0.0000,  0.0000, -0.0000,  0.2025, -0.9759],
        [ 0.0000,  0.0000,  0.0000, -0.2025, -0.0000, -0.0818],
        [ 0.0000,  0.0000,  0.0000,  0.9759,  0.0818, -0.0000],
        [ 0.0000,  0.0000,  0.0000, -0.0000,  0.9634,  0.1835],
        [ 0.0000,  0.0000,  0.0000, -0.9634, -0.0000,  0.1952],
        [ 0.0000,  0.0000,  0.0000, -0.1835, -0.1952, -0.0000],
        [ 1.0000,  0.0000,  0.0000, -0.0000,  0.3506,  0.0029],
        [ 0.0000,  1.0000,  0.0000, -0.3506, -0.0000,  0.1905],
        [ 0.0000,  0.0000,  1.0000, -0.0029, -0.1905, -0.0000]],
       dtype=torch.float64, grad_fn=<SliceBackward0>)

In [62]:
T.matrix()[:-1,0]

tensor([ 0.9773,  0.1183, -0.1755], dtype=torch.float64,
       grad_fn=<SelectBackward0>)

In [63]:
-T.matrix()

tensor([[-0.9773,  0.0818, -0.1952, -0.1905],
        [-0.1183, -0.9759,  0.1835,  0.0029],
        [ 0.1755, -0.2025, -0.9634, -0.3506],
        [-0.0000, -0.0000, -0.0000, -1.0000]], dtype=torch.float64,
       grad_fn=<NegBackward0>)

tensor([[ 1.0000,  0.0000,  0.0000,  0.0000,  0.7084, -0.5504],
        [ 0.0000,  1.0000,  0.0000, -0.7084,  0.0000,  1.1357],
        [ 0.0000,  0.0000,  1.0000,  0.5504, -1.1357,  0.0000]],
       dtype=torch.float64, grad_fn=<MmBackward0>)

In [58]:
p

tensor([1.1357, 0.5504, 0.7084], dtype=torch.float64, grad_fn=<ViewBackward0>)

In [40]:
torch.kron(T.matrix().T, torch.eye(3)) @ (torch.kron(T.matrix().T, torch.eye(3)) @ dExpxi_dxi()[:12])

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000, -0.1755, -0.1183],
        [ 0.0000,  0.0000,  0.0000,  0.1755,  0.0000,  0.9773],
        [ 0.0000,  0.0000,  0.0000,  0.1183, -0.9773,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.2025, -0.9759],
        [ 0.0000,  0.0000,  0.0000, -0.2025,  0.0000, -0.0818],
        [ 0.0000,  0.0000,  0.0000,  0.9759,  0.0818,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.9634,  0.1835],
        [ 0.0000,  0.0000,  0.0000, -0.9634,  0.0000,  0.1952],
        [ 0.0000,  0.0000,  0.0000, -0.1835, -0.1952,  0.0000],
        [ 1.0000,  0.0000,  0.0000,  0.0000,  0.3506,  0.0029],
        [ 0.0000,  1.0000,  0.0000, -0.3506,  0.0000,  0.1905],
        [ 0.0000,  0.0000,  1.0000, -0.0029, -0.1905,  0.0000]],
       dtype=torch.float64, grad_fn=<MmBackward0>)

tensor([1.1357, 0.5504, 0.7084, 1.0000], dtype=torch.float64,
       grad_fn=<CatBackward0>)

In [24]:
T.matrix()

tensor([[ 0.9773, -0.0818,  0.1952,  0.1905],
        [ 0.1183,  0.9759, -0.1835, -0.0029],
        [-0.1755,  0.2025,  0.9634,  0.3506],
        [ 0.0000,  0.0000,  0.0000,  1.0000]], dtype=torch.float64,
       grad_fn=<TransposeBackward0>)

In [12]:
(dExpxi_dxi(T.matrix()[:-1,0], T.matrix()[:-1,1], T.matrix()[:-1,2], T.matrix()[:-1,3]).T @ torch.kron(torch.cat((x,torch.tensor([1]))), torch.eye(4)).T).T

tensor([[ 0.0000,  0.0000,  0.0000, -0.1868, -0.2461, -0.1534],
        [ 0.4277,  0.0000,  0.0000,  0.6848,  0.1937,  0.9067],
        [ 0.0000,  0.4277,  0.0000, -0.0403, -0.3899,  0.1797],
        [ 0.0000,  0.0000,  0.4277, -0.5168,  0.1061, -0.7997]],
       dtype=torch.float64, grad_fn=<PermuteBackward0>)

In [13]:
torch.kron(torch.cat((x,torch.tensor([1]))), torch.eye(4)) @ dExpxi_dxi(T.matrix()[:-1,0], T.matrix()[:-1,1], T.matrix()[:-1,2], T.matrix()[:-1,3])

tensor([[ 0.0000,  0.0000,  0.0000, -0.1868, -0.2461, -0.1534],
        [ 0.4277,  0.0000,  0.0000,  0.6848,  0.1937,  0.9067],
        [ 0.0000,  0.4277,  0.0000, -0.0403, -0.3899,  0.1797],
        [ 0.0000,  0.0000,  0.4277, -0.5168,  0.1061, -0.7997]],
       dtype=torch.float64, grad_fn=<MmBackward0>)

In [17]:
p_hom = torch.cat((p,torch.tensor([1])))
2 * (dExpxi_dxi().T @ torch.kron(torch.cat((p,torch.tensor([1]))), torch.eye(4)).T) @ p_hom

tensor([ 0.7799,  1.0038,  1.4169, -0.4949, -0.8293, -1.0212],
       dtype=torch.float64, grad_fn=<MvBackward0>)

In [18]:
torch.kron(torch.cat((p,torch.tensor([1]))), torch.eye(4)).shape

torch.Size([4, 16])